### ISSUE TITLE
Authentication failing?

### ISSUE THREAD

**Issue by Meandmybadself** [comster/podcast-index-api#5]
Thanks for this library, we've found it incredibly helpful.

# Environment
* macOS Monterey
* node 16.14.0

# Issue
We've had the library running well up until recently.
Something appears to have changed when attempting to call `searchByTitle` or `searchByTerm`.
The authentication check fails, responding 401 with the following text:

```
The hash in the Authorization header doesn't match up.  
Please check your hash compute code: https: //podcastindex-org.github.io/docs-api/#overview--authentication-details
```

# Steps to recreate
I've created a barebones recreation repository here:
https://github.com/Meandmybadself/podcast-index-api-test

# Items I've looked into:

* Ensured that the latest (1.1.10) was installed.
* Tried 3 different sets of API keys.  All respond the same.
* Tried looking through the source.  Appears that `X-Auth-Key` is being hashed in line with their expectations.
* Looked to see if the X-Auth-Date aspect has changed (maybe from seconds to milliseconds?).  It has not.
* Tried rounding the number for X-Auth-Date down to eliminate decimals per API spec.
 
Am I messing up how one supplies credentials?

**Comment by comster** [comment]
I'm not sure if something has changed.
Do some API calls work, just not those 2? (searchByTitle or searchByTerm)

**Comment by seagullmouse** [comment]
Just in case you hit the same problem as me. My secret had a `$` in it. This was actually ending the secret string as far as my .env file was concerned. The solution was to escape it `\$`.

**Comment by Meandmybadself** [comment]
@seagullmouse - This was our issue.  Thank you.
